### ISSUE TITLE
Project IRC Channel

### ISSUE THREAD

**Issue by Thumperrr** [cpluspluscom/ChessPlusPlus#18]
irc.freenode.net #ChessPlusPlus

Posting this in the issues so it doesn't get buried in the forums.

**Comment by LB--** [comment]
Just so everyone knows, I won't be using the IRC anymore - I much prefer Gitter. ResidentBiscuit and several others are already using it. The nice thing is being able to see chat history from when you were offline.

**Comment by LB--** [comment]
Should we remove the IRC channel from the README? Nobody seems to use it anymore in favor of Gitter - every time I've checked in it's just been @usandfriends and/or @naraku9333 online, and usually nobody's OP. Gitter supports GitHub-flavored Markdown, it integrates with GitHub so people can't be impersonated, and it stores message history from when you are offline so you never miss anything. Lots of other open source projects are Gitter-only too. There's also a consistent web client, native client, and mobile client.

Personally I would prefer if all communication happened in Gitter rather than being split into two places with one of those places not preserving history.

**Comment by usandfriends** [comment]
I would say get rid of the channel. Gitter is becoming the norm for chat for Github-hosted projects as it styles Github URLs and allows Markdown in chat.

<i>Note: There's a Travis-CI bot that prints if builds succeeded or failed in the IRC channel. Are you going to set up a Travis-CI webhook for this repository to post similar info in Gitter?</i>

**Comment by LB--** [comment]
@usandfriends Gitter already has the webhooks setup, including for Travis - they get posted to the right sidebar.

**Comment by usandfriends** [comment]
@LB-- Perfect, thank you.
